using OpenTK.Mathematics;
using RetroEngine.Core;
using System.ComponentModel;

namespace RetroEngine.Graphics
{
    /// <summary>
    /// Defines functions for Camera component.
    /// </summary>
    public static class CameraExtensions
    {
        /// <summary>
        /// Gets clip space matrices generated by this camera.
        /// </summary>
        /// <param name="component">Component to manipulate.</param>
        /// <param name="transform">Transform component of the entity having this camera.</param>
        /// <param name="width">Camera's pixel width.</param>
        /// <param name="height">Camea's pixel height.</param>
        /// <returns>An instance of a ClipSpace.</returns>
        public static ClipSpace GetClipSpace(this Camera component, Transform transform, int width, int height)
        {
            var view = Matrix4.LookAt(
                    new Vector3(transform.Position),
                    new Vector3(transform.Position) + component.Front,
                    component.Up);

            var projection = component.Projection == ProjectionType.Orthographic ?
                Matrix4.CreateOrthographicOffCenter(
                    -width / 100,
                    width / 100,
                    -height / 100,
                    height / 100,
                    component.ClippingNear,
                    component.ClippingFar)
                :
                Matrix4.CreatePerspectiveFieldOfView(
                    component.FieldOfView,
                    (float)width / height,
                    component.ClippingNear,
                    component.ClippingFar);

            return new ClipSpace() { View = view, Projection = projection };
        }

        /// <summary>
        /// Updates the camera vectors based on a transform component.
        /// </summary>
        /// <param name="component">Component to manipulate.</param>
        /// <param name="transform">Transform component of the entity having this camera.</param>
        public static void UpdateCameraVectors(this ref Camera component, Transform transform)
        {
            var frontX = (float)Math.Round(MathHelper.Cos(transform.Rotation.X), 6) * (float)Math.Round(MathHelper.Sin(transform.Rotation.Y), 6);
            var frontY = (float)Math.Round(MathHelper.Sin(transform.Rotation.X), 6);
            var frontZ = (float)Math.Round(MathHelper.Cos(transform.Rotation.X), 6) * (float)Math.Round(MathHelper.Cos(transform.Rotation.Y), 6);

            component.Front = Vector3.Normalize(new Vector3(frontX, frontY, -frontZ));
            component.Right = Vector3.Normalize(Vector3.Cross(component.Front, Vector3.UnitY));
            component.Up = Vector3.Normalize(Vector3.Cross(component.Right, component.Front));
        }

        /// <summary>
        /// Performs a translate on a camera transform component to move the camara forward.
        /// </summary>
        /// <param name="component">Component to manipulate.</param>
        /// <param name="transform">Transform component of the camera.</param>
        /// <param name="module">Units to move.</param>
        public static void MoveForward(this Camera component, ref Transform transform, float module)
        {
            transform.Translate(component.Front * module);
        }

        /// <summary>
        /// Performs a translate on a camera transform component to move the camara backwards.
        /// </summary>
        /// <param name="component">Component to manipulate.</param>
        /// <param name="transform">Transform component of the camera.</param>
        /// <param name="module">Units to move.</param>
        public static void MoveBackwards(this Camera component, ref Transform transform, float module)
        {
            transform.Translate(component.Front * -module);
        }

        /// <summary>
        /// Performs a translate on a camera transform component to move the camara up.
        /// </summary>
        /// <param name="component">Component to manipulate.</param>
        /// <param name="transform">Transform component of the camera.</param>
        /// <param name="module">Units to move.</param>
        public static void MoveUp(this Camera component, ref Transform transform, float module)
        {
            transform.Translate(Vector3.UnitY * module);
        }

        /// <summary>
        /// Performs a translate on the camera transform component to move the camara down.
        /// </summary>
        /// <param name="component">Component to manipulate.</param>
        /// <param name="transform">Transform component of the camera.</param>
        /// <param name="module">Units to move.</param>
        public static void MoveDown(this Camera component, ref Transform transform, float module)
        {
            transform.Translate(Vector3.UnitY * -module);
        }

        /// <summary>
        /// Performs a translate on the camera transform component to move the camara left.
        /// </summary>
        /// <param name="component">Component to manipulate.</param>
        /// <param name="transform">Transform component of the camera.</param>
        /// <param name="module">Units to move.</param>
        public static void MoveLeft(this Camera component, ref Transform transform, float module)
        {
            transform.Translate(component.Right * -module);
        }

        /// <summary>
        /// Performs a translate on the camera transform component to move the camara right.
        /// </summary>
        /// <param name="component">Component to manipulate.</param>
        /// <param name="transform">Transform component of the camera.</param>
        /// <param name="module">Units to move.</param>
        public static void MoveRight(this Camera component, ref Transform transform, float module)
        {
            transform.Translate(component.Right * module);
        }

        /// <summary>
        /// Performs a rotation on the camera transform component to make the camera look up.
        /// </summary>
        /// <param name="component">Component to manipulate.</param>
        /// <param name="transform">Transform component of the camera.</param>
        /// <param name="module">Units to rotate.</param>
        public static void LookUp(this Camera component, ref Transform transform, float module)
        {
            transform.Rotate(Vector3.UnitX * module);
        }

        /// <summary>
        /// Performs a rotation on the camera transform component to make the camera look down.
        /// </summary>
        /// <param name="component">Component to manipulate.</param>
        /// <param name="transform">Transform component of the camera.</param>
        /// <param name="module">Units to rotate.</param>
        public static void LookDown(this Camera component, ref Transform transform, float module)
        {
            transform.Rotate(Vector3.UnitX * -module);
        }

        /// <summary>
        /// Performs a rotation on the camera transform component to make the camera look left.
        /// </summary>
        /// <param name="component">Component to manipulate.</param>
        /// <param name="transform">Transform component of the camera.</param>
        /// <param name="module">Units to rotate.</param>
        public static void LookLeft(this Camera component, ref Transform transform, float module)
        {
            transform.Rotate(Vector3.UnitY * -module);
        }

        /// <summary>
        /// Performs a rotation on the camera transform component to make the camera look right.
        /// </summary>
        /// <param name="component">Component to manipulate.</param>
        /// <param name="transform">Transform component of the camera.</param>
        /// <param name="module">Units to rotate.</param>
        public static void LookRight(this Camera component, ref Transform transform, float module)
        {
            transform.Rotate(Vector3.UnitY * module);
        }
    }
}
