using OpenTK.Mathematics;
using RetroEngine.Core;

namespace RetroEngine.Graphics
{
    /// <summary>
    /// Defines a camera view component.
    /// </summary>
    public struct Camera()
    {
        private Vector3 _front = -Vector3.UnitZ;
        private Vector3 _right = Vector3.UnitX;
        private Vector3 _up = Vector3.UnitY;

        /// <summary>
        /// Gets or sets the background used to clear the view of the camera.
        /// </summary>
        public Color4 Background { get; set; } = Color4.CornflowerBlue;

        /// <summary>
        /// Gets or sets the projection of the camera.
        /// </summary>
        public ProjectionType Projection { get; set; } = ProjectionType.Orthographic;

        /// <summary>
        /// Gets or sets the field of view for the perspective view.
        /// </summary>
        /// <remarks>This property is used just for the perspective projection.</remarks>
        public float FieldOfView { get; set; } = MathHelper.PiOver4;

        /// <summary>
        /// Gets or sets the nearest plane rendered by the camera.
        /// </summary>
        public float ClippingNear { get; set; } = .3f;

        /// <summary>
        /// Gets or sets the farthest plane rendered by the camera.
        /// </summary>
        public float ClippingFar { get; set; } = 1000f;

        /// <summary>
        /// Gets clip space matrices generated by this camera.
        /// </summary>
        /// <param name="transform">Transform component of the entity having this camera.</param>
        /// <param name="width">Camera's pixel width.</param>
        /// <param name="height">Camea's pixel height.</param>
        /// <returns>An instance of a ClipSpace.</returns>
        public ClipSpace GetClipSpace(Transform transform, int width, int height)
        {
            var view = Matrix4.LookAt(
                    new Vector3(transform.Position),
                    new Vector3(transform.Position) + _front,
                    _up);

            var projection = Projection == ProjectionType.Orthographic ?
                Matrix4.CreateOrthographicOffCenter(
                    -width / 100,
                    width / 100,
                    -height / 100,
                    height / 100,
                    ClippingNear,
                    ClippingFar)
                :
                Matrix4.CreatePerspectiveFieldOfView(
                    FieldOfView,
                    (float) width / height,
                    ClippingNear,
                    ClippingFar);

            return new ClipSpace() { View = view, Projection = projection };
        }

        /// <summary>
        /// Updates the camera vectors based on a transform component.
        /// </summary>
        /// <param name="transform">Transform component of the entity having this camera.</param>
        public void UpdateCameraVectors(Transform transform)
        {
            var frontX = (float)Math.Round(MathHelper.Cos(transform.Rotation.X), 6) * (float)Math.Round(MathHelper.Sin(transform.Rotation.Y), 6);
            var frontY = (float)Math.Round(MathHelper.Sin(transform.Rotation.X), 6);
            var frontZ = (float)Math.Round(MathHelper.Cos(transform.Rotation.X), 6) * (float)Math.Round(MathHelper.Cos(transform.Rotation.Y), 6);

            _front = Vector3.Normalize(new Vector3(frontX, frontY, -frontZ));
            _right = Vector3.Normalize(Vector3.Cross(_front, Vector3.UnitY));
            _up = Vector3.Normalize(Vector3.Cross(_right, _front));
        }

        /// <summary>
        /// Performs a translate on a camera transform component to move the camara forward.
        /// </summary>
        /// <param name="transform">Transform component of the camera.</param>
        /// <param name="module">Units to move.</param>
        /// <returns>New transform component with the translation applied.</returns>
        public readonly Transform MoveForward(Transform transform, float module)
        {
            transform.Translate(_front * module);
            return transform;
        }

        /// <summary>
        /// Performs a translate on a camera transform component to move the camara backwards.
        /// </summary>
        /// <param name="transform">Transform component of the camera.</param>
        /// <param name="module">Units to move.</param>
        /// <returns>New transform component with the translation applied.</returns>
        public readonly Transform MoveBackwards(Transform transform, float module)
        {
            transform.Translate(_front * -module);
            return transform;
        }

        /// <summary>
        /// Performs a translate on a camera transform component to move the camara up.
        /// </summary>
        /// <param name="transform">Transform component of the camera.</param>
        /// <param name="module">Units to move.</param>
        /// <returns>New transform component with the translation applied.</returns>
        public readonly Transform MoveUp(Transform transform, float module)
        {
            transform.Translate(Vector3.UnitY * module);
            return transform;
        }

        /// <summary>
        /// Performs a translate on the camera transform component to move the camara down.
        /// </summary>
        /// <param name="transform">Transform component of the camera.</param>
        /// <param name="module">Units to move.</param>
        /// <returns>New transform component with the translation applied.</returns>
        public readonly Transform MoveDown(Transform transform, float module)
        {
            transform.Translate(Vector3.UnitY * -module);
            return transform;
        }

        /// <summary>
        /// Performs a translate on the camera transform component to move the camara left.
        /// </summary>
        /// <param name="transform">Transform component of the camera.</param>
        /// <param name="module">Units to move.</param>
        /// <returns>New transform component with the translation applied.</returns>
        public readonly Transform MoveLeft(Transform transform, float module)
        {
            transform.Translate(_right * -module);
            return transform;
        }

        /// <summary>
        /// Performs a translate on the camera transform component to move the camara right.
        /// </summary>
        /// <param name="transform">Transform component of the camera.</param>
        /// <param name="module">Units to move.</param>
        /// <returns>New transform component with the translation applied.</returns>
        public readonly Transform MoveRight(Transform transform, float module)
        {
            transform.Translate(_right * module);
            return transform;
        }

        /// <summary>
        /// Performs a rotation on the camera transform component to make the camera look up.
        /// </summary>
        /// <param name="transform">Transform component of the camera.</param>
        /// <param name="module">Units to rotate.</param>
        /// <returns>New transform component with the rotation applied.</returns>
        public readonly Transform LookUp(Transform transform, float module)
        {
            transform.Rotate(Vector3.UnitX * module);
            return transform;
        }

        /// <summary>
        /// Performs a rotation on the camera transform component to make the camera look down.
        /// </summary>
        /// <param name="transform">Transform component of the camera.</param>
        /// <param name="module">Units to rotate.</param>
        /// <returns>New transform component with the rotation applied.</returns>
        public readonly Transform LookDown(Transform transform, float module)
        {
            transform.Rotate(Vector3.UnitX * -module);
            return transform;
        }

        /// <summary>
        /// Performs a rotation on the camera transform component to make the camera look left.
        /// </summary>
        /// <param name="transform">Transform component of the camera.</param>
        /// <param name="module">Units to rotate.</param>
        /// <returns>New transform component with the rotation applied.</returns>
        public readonly Transform LookLeft(Transform transform, float module)
        {
            transform.Rotate(Vector3.UnitY * -module);
            return transform;
        }

        /// <summary>
        /// Performs a rotation on the camera transform component to make the camera look right.
        /// </summary>
        /// <param name="transform">Transform component of the camera.</param>
        /// <param name="module">Units to rotate.</param>
        /// <returns>New transform component with the rotation applied.</returns>
        public readonly Transform LookRight(Transform transform, float module)
        {
            transform.Rotate(Vector3.UnitY * module);
            return transform;
        }
    }
}
