<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RetroEngine.Buddies\RetroEngine.Buddies.csproj" />
    <ProjectReference Include="..\RetroEngine.Core\RetroEngine.Core.csproj" />
    <ProjectReference Include="..\RetroEngine.Graphics\RetroEngine.Graphics.csproj" />
  </ItemGroup>

</Project>
