name: Bug Report
description: Report of a bug in the code.
title: "Bug: "
labels: ["🛠 type: bug", "⏳ status: pending", "🚦 priority: need triage"]
assignees:
  - retromannfred
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Describe what is happening or what is the current behaviour of the engine.
      placeholder: The code is...
    validations:
      required: true
  - type: textarea
    attributes:
      label: How it should work?
      description: Describe how actually should work or how the current behaviour of the engine should be.
      placeholder: The code should...
    validations:
      required: true
  - type: textarea
    attributes:
      label: How it can be reproduced?
      description: Explain how the bug can be reproducen in a run.
      placeholder: The steps are...
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### Select the affected libraries
        Use the checkboxes below to indicate which parts of the engine are or may be affected by this bug.
  - type: boolean
    attributes:
      label: RetroEngine.Core
  - type: boolean
    attributes:
      label: RetroEngine.Graphics
  - type: boolean
    attributes:
      label: RetroEngine.Audio
  - type: boolean
    attributes:
      label: RetroEngine.Physics