namespace RetroEngine.Core
{
    /// <summary>
    /// Defines a group of graphic settings of a game.
    /// </summary>
    /// <param name="width">With of the screen.</param>
    /// <param name="height">Height of the screen.</param>
    public class GraphicSettings(int width, int height)
    {
        /// <summary>
        /// Gets the width of the window.
        /// </summary>
        public int Width { get; internal set; } = width;

        /// <summary>
        /// Gets the height of the window.
        /// </summary>
        public int Height { get; internal set; } = height;

        /// <summary>
        /// Gets the aspect ratio of the window (width / height).
        /// </summary>
        public float AspectRatio
        {
            get { return (float)Width / Height; }
        }

        /// <summary>
        /// Gets the clip space matrices generated by the cameras in the scene.
        /// </summary>
        public List<ClipSpace> ClipSpaces { get; internal set; } = [];
    }
}
