<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Shaders\Defaults\fragment.glsl" />
    <None Remove="Shaders\Defaults\vertex.glsl" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Shaders\Defaults\fragment.glsl" />
    <EmbeddedResource Include="Shaders\Defaults\vertex.glsl" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RetroEngine.Core\RetroEngine.Core.csproj" />
  </ItemGroup>

</Project>
